#!/usr/bin/env python

"""
Node for doing checks on the costmap that move_base won't do
"""

import rospy, rospkg
import networkx as nx
from lamp import EdgeObserver, tgraph

PKGDIR = rospkg.RosPack().get_path('lamp')
# MAP = 'tristan_maze'
MAP = 'test_large'

if __name__ == '__main__':
    graph = nx.read_yaml(PKGDIR + '/maps/' + MAP + '/' + MAP + '_tgraph.yaml')
    poly_dict = tgraph.polygon_dict_from_csv(PKGDIR + '/maps/' + MAP + '/' + MAP + '_polygons.csv')

    base_graph = tgraph.TGraph(graph, poly_dict)

    try:
        EdgeObserver(base_graph)
    except rospy.ROSInterruptException:
        pass
