#!/usr/bin/env python
import logging
logger = logging.getLogger(__name__)
import rospy, rospkg
import networkx as nx

from lamp import Lamp, tgraph

PKGDIR = rospkg.RosPack().get_path('lamp')
# MAP = 'tristan_maze'
MAP = 'test_large'

NTASKS = 5 # number of tasks to execute in trial

if __name__ == '__main__':
    # load nxgraph and polygon information
    graph = nx.read_yaml(PKGDIR + '/maps/' + MAP + '/' + MAP + '_tgraph.yaml')
    poly_dict = tgraph.polygon_dict_from_csv(PKGDIR + '/maps/' + MAP + '/' + MAP + '_polygons.csv')

    # setup logging
    logging.basicConfig(level=logging.DEBUG)

    # run LRPP
    try:
        Lamp(graph, poly_dict, T=NTASKS)
    except rospy.ROSInterruptException:
        rospy.loginfo("Finished simulation.")
